# Check out https://docs.codemagic.io/getting-started/building-a-native-ios-app/ for more information
# Please review and update values in curly braces

workflows:
    ios-app:
        name: iOS App
        environment:
            vars:
                XCODE_PROJECT: "Cleanish Clock.xcodeproj"
                XCODE_SCHEME: "Cleanish Clock"
            xcode: latest
            cocoapods: default
        scripts:
            - xcodebuild build -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        artifacts:
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
